# Description: WIREGUARD
[Interface]
PrivateKey = <SERVER_PRIVATE_KEY>
ListenPort = 51820

# Peer: KatanaF Laptop
[Peer]
PublicKey = <CLIENT_PUBLIC_KEY>
PresharedKey = <CLIENT_PRESHARED_KEY>
AllowedIPs = 10.8.0.2/32
PersistentKeepalive = 0